
project_id = "nxmbadblisjgqdmhwrmz"

[functions.ai-text-generation]
verify_jwt = true

[functions.ai-speech-recognition]
verify_jwt = true

[functions.ai-text-to-speech]
verify_jwt = true

[functions.ai-grammar-analysis]
verify_jwt = true

[functions.ai-translation]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions]
[functions.import]
include = ["node_modules"]

[global.env_variables]
OPENAI_API_KEY = "{{OPENAI_API_KEY}}"
HUGGING_FACE_API_KEY = "{{HUGGING_FACE_API_KEY}}"
