
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { BarChart, LineChart } from "@/components/ui/charts";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { PieChart, ResponsiveContainer } from "recharts";
import { Lightbulb, Brain, Zap, CalendarClock, LineChart as LineChartIcon, BarChart2 } from "lucide-react";
import { useAIUtils } from '@/contexts/AIUtilsContext';

const LearningInsightsReport = () => {
  const { isProcessing } = useAIUtils();
  
  // Sample data - in a real app, this would come from the user's actual learning history
  const weeklyProgressData = [
    { name: "Mon", progress: 65 },
    { name: "Tue", progress: 40 },
    { name: "Wed", progress: 75 },
    { name: "Thu", progress: 55 },
    { name: "Fri", progress: 60 },
    { name: "Sat", progress: 80 },
    { name: "Sun", progress: 70 },
  ];
  
  const categoryPerformanceData = [
    { name: "Vocabulary", score: 75 },
    { name: "Grammar", score: 60 },
    { name: "Listening", score: 50 },
    { name: "Speaking", score: 65 },
    { name: "Writing", score: 70 },
  ];
  
  const upcomingReviewsData = [
    { name: "Today", reviews: 12 },
    { name: "Tomorrow", reviews: 8 },
    { name: "2 Days", reviews: 15 },
    { name: "3 Days", reviews: 6 },
    { name: "4 Days", reviews: 10 },
    { name: "5 Days", reviews: 4 },
    { name: "6 Days", reviews: 7 },
  ];
  
  const timeOfDayData = [
    { name: "Morning", performance: 85 },
    { name: "Afternoon", performance: 70 },
    { name: "Evening", performance: 60 },
    { name: "Night", performance: 50 },
  ];
  
  // Sample insights - in a real app, these would be generated by AI
  const insights = [
    "Your vocabulary retention is 23% higher when you practice in the morning",
    "You perform best on grammar exercises after completing vocabulary reviews",
    "Your learning efficiency increases by 15% when sessions are kept under 25 minutes",
    "Speaking practice has improved your listening comprehension by 18%",
    "Your weekend study sessions are 30% more productive than weekday sessions"
  ];
  
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center">
              <Lightbulb className="h-4 w-4 mr-2 text-yellow-500" />
              Optimal Time
            </CardTitle>
            <CardDescription>Best learning period</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">Morning</div>
            <p className="text-xs text-muted-foreground">85% effectiveness</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center">
              <Brain className="h-4 w-4 mr-2 text-violet-500" />
              Strengths
            </CardTitle>
            <CardDescription>Your strong areas</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">Vocabulary</div>
            <p className="text-xs text-muted-foreground">75% proficiency</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center">
              <Zap className="h-4 w-4 mr-2 text-amber-500" />
              Study Streak
            </CardTitle>
            <CardDescription>Consecutive days</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">7 days</div>
            <p className="text-xs text-muted-foreground">Current streak</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center">
              <CalendarClock className="h-4 w-4 mr-2 text-blue-500" />
              Due Reviews
            </CardTitle>
            <CardDescription>Today's agenda</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">12 cards</div>
            <p className="text-xs text-muted-foreground">+8 tomorrow</p>
          </CardContent>
        </Card>
      </div>
      
      <Tabs defaultValue="progress">
        <TabsList className="grid grid-cols-2 md:grid-cols-4 mb-4">
          <TabsTrigger value="progress" className="flex items-center gap-2">
            <LineChartIcon className="h-4 w-4" />
            <span className="hidden sm:inline">Progress</span>
          </TabsTrigger>
          <TabsTrigger value="performance" className="flex items-center gap-2">
            <BarChart2 className="h-4 w-4" />
            <span className="hidden sm:inline">Performance</span>
          </TabsTrigger>
          <TabsTrigger value="reviews" className="flex items-center gap-2">
            <CalendarClock className="h-4 w-4" />
            <span className="hidden sm:inline">Reviews</span>
          </TabsTrigger>
          <TabsTrigger value="insights" className="flex items-center gap-2">
            <Lightbulb className="h-4 w-4" />
            <span className="hidden sm:inline">Insights</span>
          </TabsTrigger>
        </TabsList>
        
        <TabsContent value="progress">
          <Card>
            <CardHeader>
              <CardTitle>Weekly Learning Progress</CardTitle>
              <CardDescription>Your daily learning activity over the past week</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart 
                    data={weeklyProgressData}
                    index="name"
                    categories={["progress"]}
                    colors={["blue"]}
                    valueFormatter={(value: number) => `${value}%`}
                  />
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="performance">
          <Card>
            <CardHeader>
              <CardTitle>Category Performance</CardTitle>
              <CardDescription>Your proficiency across different learning categories</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart 
                    data={categoryPerformanceData}
                    index="name"
                    categories={["score"]}
                    colors={["green"]}
                    valueFormatter={(value: number) => `${value}%`}
                  />
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="reviews">
          <Card>
            <CardHeader>
              <CardTitle>Upcoming Reviews</CardTitle>
              <CardDescription>Number of reviews due in the coming days</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart 
                    data={upcomingReviewsData}
                    index="name"
                    categories={["reviews"]}
                    colors={["purple"]}
                    valueFormatter={(value: number) => `${value} cards`}
                  />
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="insights">
          <Card>
            <CardHeader>
              <CardTitle>AI-Generated Insights</CardTitle>
              <CardDescription>Personalized observations about your learning patterns</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {insights.map((insight, index) => (
                  <li key={index} className="flex items-start gap-2 p-2 rounded hover:bg-muted">
                    <Lightbulb className="h-5 w-5 text-yellow-500 mt-0.5 flex-shrink-0" />
                    <span>{insight}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default LearningInsightsReport;
