name: End-to-End Tests  

on:  
  push:  
    branches: [ main, master, develop ]  
  pull_request:  
    branches: [ main, master, develop ]  

jobs:  
  cypress-run:  
    runs-on: ubuntu-latest  
    container:  
      image: cypress/browsers:latest  
      options: --user 1001  
    
    strategy:  
      fail-fast: false  
      matrix:  
        # Run multiple copies of the current job in parallel  
        containers: [1, 2, 3, 4]  
    
    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  
      
      - name: Install Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: 18  
      
      - name: Install dependencies  
        run: npm ci  
      
      - name: Verify Cypress  
        run: npx cypress verify  
      
      - name: Cypress run  
        uses: cypress-io/github-action@v5  
        with:  
          browser: chrome  
          build: npm run build  
          start: npm run preview  
          wait-on: 'http://localhost:4173'  
          record: true  
          parallel: true  
          group: 'UI Tests'  
          spec: cypress/e2e/**/*.cy.{js,jsx,ts,tsx}  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}  
          CYPRESS_baseUrl: http://localhost:4173  
      
      - name: Upload Cypress screenshots  
        if: failure()  
        uses: actions/upload-artifact@v2  # Changed to v2  
        with:  
          name: cypress-screenshots-${{ matrix.containers }}  
          path: cypress/screenshots  
      
      - name: Upload Cypress videos  
        if: always()  
        uses: actions/upload-artifact@v2  # Changed to v2  
        with:  
          name: cypress-videos-${{ matrix.containers }}  
          path: cypress/videos  
