name: Comprehensive Debug Workflow  
on: [push, pull_request]  

jobs:  
  debug:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v3  
    
    - name: Setup Node.js  
      uses: actions/setup-node@v3  
      with:  
        node-version: '18'  
    
    - name: Install Dependencies  
      run: |  
        npm install  
        npm install -g typescript @types/react  
    
    - name: TypeScript Compilation Check  
      run: |  
        npx tsc --noEmit --pretty  
    
    - name: Dependency Audit  
      run: |  
        npm audit  
    
    - name: List Installed Packages  
      run: |  
        npm list --depth=1  
    
    - name: Check for Unresolved Modules  
      run: |  
        find . -name "*.ts" -o -name "*.tsx" | xargs grep -l "import.*from"
